### ISSUE TITLE
I managed to compile it. And when I ran it, I just get empty world. How do you add the blocks or implement them? 

### ISSUE THREAD

**Issue by h1s0k429a** [agausmann/wiregrid#2]
I looked into the source code and there's no code to process block insertion. Only panning and moving the camera around. But I also saw the inverter code in the examples. How do you include that to compile with the main library?

**Comment by agausmann** [comment]
You're right, that code does not exist at all yet. There is simulation support for the inverter, but I haven't added circuit editing to the frontend. The screenshot I put in the README was just a drawing I made with an older renderer. Sorry if it misled you into thinking this was ready to use.

This project is still far from being usable, and even farther from being a complete product. At the moment it's sitting near the top of my backlog of projects, it's temporarily stalled while I work on some other things. I do appreciate your enthusiasm and support though, I hope you'll continue to follow it!

**Comment by h1s0k429a** [comment]
Thank you for clearing that out. 

The project looks like something that I would invest hours into playing.
